### ISSUE TITLE
add pictures to home page 

### ISSUE THREAD

**Issue by 11131807** [11131807/11131807.github.io#2]
![car](https://user-images.githubusercontent.com/131965709/236177512-9380db53-0887-40c5-8199-677ca62ab110.jpeg)

**Comment by jhawlc** [comment]
Don't add pictures to your task list. They need to be added to the actual website.
https://drive.google.com/file/d/1Nvy72wn8lU60Ku4brI3GF7gZzgg6mBSZ/view
